ulib: ulib::CUTreeNode Class Reference
ulib::CUTreeNode Class Reference
#include <utree.h>
Public Member Functions
CUTreeNode ()
~CUTreeNode ()
void AddChild (CUTreeNode *child)
CUTreeNode * GetChild (int idx)
Public Member Functions inherited from ulib::CUNode
CUNode ()
~CUNode ()
bool SetData (void *arg_data, short arg_data_size)
bool GetData (void *ret_data)
void Clear ()
bool IsEmpty ()
void Verbose (int arg_verbose)
Public Attributes
CUTreeNode * parent
CUList child_list
Public Attributes inherited from ulib::CUNode
int id
void * data
size_t data_size
Constructor & Destructor Documentation
ulib::CUTreeNode::CUTreeNode ()
ulib::CUTreeNode::~CUTreeNode ()
Member Function Documentation
void ulib::CUTreeNode::AddChild (CUTreeNode * child)
References child_list, and ulib::CUList::PushBack().
Referenced by ulib::CUTree::AddChildNode().
CUTreeNode * ulib::CUTreeNode::GetChild (int idx)
References child_list, and ulib::CUList::GetAt().
Referenced by ulib::CUTree::Print().
Member Data Documentation
CUList ulib::CUTreeNode::child_list
Referenced by AddChild(), GetChild(), and ulib::CUTree::Print().
CUTreeNode* ulib::CUTreeNode::parent
Referenced by ulib::CUTree::AddChildNode().
The documentation for this class was generated from the following files:
include/utree.h
src/uadt/utree.cpp