ulib: ulib Namespace Reference
ulib Namespace Reference
Classes
class CUConfigFile
Configure 클래스
class CUCounter
class CUDir
class CUFile
class CUFlistFile
class CUIndexFileInfo
class CUIndexFile
class CUJsonItem
class CUJsonContainer
class CUJsonToken
class CUJsonTokenList
class CUJson
class CUListNode
List Node.
class CUList
class CUMath
class CUNode
class CUOption
class CUParser
class CUProgress
class CUStackNode
Stack Node 클래스
class CUStack
Stack 클래스
class CUString
String 클래스
class CUStringList
StringList 클래스
class CUStringListRO
StringList 클래스, Null로 나누어져 있어 빠름.
class CUStringNode
class CUTextFile
class CUTreeNode
class CUTree
Typedefs
typedef map< string, CUJsonItem > item_map_t
Functions
bool LoadTextFile (char filename[], CUString &file_content)
bool GetElementByBoundTag (CUString &str, CUString &ret, char start[], char end[])
CUString Bool2Str (bool expr)
bool Str2Bool (CUString str)
int Str2Int (CUString str)
double Str2Real (CUString str)
Typedef Documentation
typedef map<string, CUJsonItem> ulib::item_map_t
Function Documentation
CUString ulib::Bool2Str (bool expr)
bool ulib::GetElementByBoundTag (CUString & str, CUString & ret, char start[], char end[])
References ulib::CUString::Find(), and ulib::CUString::SubStr().
bool ulib::LoadTextFile (char filename[], CUString & file_content)
References ulib::CUTextFile::GetFP(), and ulib::CUTextFile::IsOpen().
bool ulib::Str2Bool (CUString str)
References ulib::CUString::MakeToUpper().
int ulib::Str2Int (CUString str)
References ulib::CUString::GetStr().
double ulib::Str2Real (CUString str)
References ulib::CUString::GetStr().