ulib: ulib::CUTextFile Class Reference
ulib::CUTextFile Class Reference
#include <utextfile.h>
Public Member Functions
CUTextFile (int verbosity=0)
CUTextFile (CUString arg_file_name, CUString arg_file_mode="rb", int verbosity=0)
~CUTextFile ()
void Verbosity (int arg_verbosity)
bool IsOpen ()
bool OpenFile (CUString arg_file_name, CUString arg_file_mode="r")
bool CheckOpen (FILE *fp=stderr)
void CloseFile ()
bool ReopenFile (CUString arg_file_name, CUString arg_file_mode="r")
FILE * GetFP ()
void MoveToStart ()
void MoveToEnd ()
long GetFileSize ()
CUString GetFileName ()
CUString GetFileMode ()
long GetNumLine ()
bool MoveToLine (long sel_line)
bool ReadLine (CUString &str)
char * ReadLine ()
bool WriteLine (CUString str)
bool WriteLog (CUString str)
bool LoadToStr (CUString &str)
Constructor & Destructor Documentation
ulib::CUTextFile::CUTextFile (int verbosity = 0)
References Verbosity().
ulib::CUTextFile::CUTextFile (CUString arg_file_name, CUString arg_file_mode = "rb", int verbosity = 0)
References OpenFile(), and Verbosity().
ulib::CUTextFile::~CUTextFile ()
References CloseFile().
Member Function Documentation
bool ulib::CUTextFile::CheckOpen (FILE * fp = stderr)
References GetFileName(), ulib::CUString::GetStr(), IsOpen(), and ulib::CUString::SetColor().
Referenced by ulib::CUFlistFile::CheckOpen().
void ulib::CUTextFile::CloseFile ()
Referenced by ulib::CUIndexFile::Close(), ReopenFile(), and ~CUTextFile().
CUString ulib::CUTextFile::GetFileMode ()
CUString ulib::CUTextFile::GetFileName ()
Referenced by CheckOpen().
long ulib::CUTextFile::GetFileSize ()
FILE * ulib::CUTextFile::GetFP ()
Referenced by GetNumLine(), ulib::CUIndexFile::GetValue(), ulib::CUIndexFile::Insert(), ulib::LoadTextFile(), LoadToStr(), MoveToLine(), ReadLine(), WriteLine(), and WriteLog().
long ulib::CUTextFile::GetNumLine ()
References GetFP(), IsOpen(), MoveToEnd(), MoveToStart(), UFILE_BUFF_SIZE, and UNKNOWN.
bool ulib::CUTextFile::IsOpen ()
Referenced by ulib::CUFlistFile::CheckList(), CheckOpen(), ulib::CUIndexFile::Close(), ulib::CUFlistFile::GetFileContent(), GetNumLine(), ulib::CUConfigFile::IsLoad(), ulib::CUIndexFile::IsLoaded(), ulib::CUFlistFile::IsOpen(), ulib::CUConfigFile::Load(), ulib::LoadTextFile(), LoadToStr(), MoveToEnd(), MoveToLine(), MoveToStart(), ReadLine(), WriteLine(), and WriteLog().
bool ulib::CUTextFile::LoadToStr (CUString & str)
References ulib::CUString::Empty(), GetFP(), IsOpen(), MoveToStart(), and ulib::CUString::Replace().
Referenced by ulib::CUFlistFile::GetFileContent().
void ulib::CUTextFile::MoveToEnd ()
References IsOpen().
Referenced by GetNumLine(), MoveToLine(), and OpenFile().
bool ulib::CUTextFile::MoveToLine (long sel_line)
References GetFP(), IsOpen(), MoveToEnd(), MoveToStart(), and UFILE_BUFF_SIZE.
void ulib::CUTextFile::MoveToStart ()
References IsOpen().
Referenced by GetNumLine(), ulib::CUConfigFile::Load(), LoadToStr(), MoveToLine(), and OpenFile().
bool ulib::CUTextFile::OpenFile (CUString arg_file_name, CUString arg_file_mode = "r")
References ulib::CUString::GetStr(), ulib::CUString::IsEmpty(), MoveToEnd(), and MoveToStart().
Referenced by ulib::CUIndexFile::Create(), CUTextFile(), ulib::CUIndexFile::Load(), ulib::CUConfigFile::Load(), ulib::CUFlistFile::Open(), and ReopenFile().
bool ulib::CUTextFile::ReadLine (CUString & str)
References ulib::CUString::Empty(), GetFP(), IsOpen(), ulib::CUString::Replace(), ulib::CUString::TrimRight(), and UFILE_BUFF_SIZE.
Referenced by ulib::CUIndexFile::Load(), ulib::CUConfigFile::Load(), and ulib::CUFlistFile::Open().
char * ulib::CUTextFile::ReadLine ()
bool ulib::CUTextFile::ReopenFile (CUString arg_file_name, CUString arg_file_mode = "r")
References CloseFile(), ulib::CUString::GetStr(), and OpenFile().
void ulib::CUTextFile::Verbosity (int arg_verbosity)
Referenced by CUTextFile().
bool ulib::CUTextFile::WriteLine (CUString str)
References GetFP(), ulib::CUString::GetStr(), and IsOpen().
bool ulib::CUTextFile::WriteLog (CUString str)
References GetFP(), ulib::CUString::GetStr(), and IsOpen().
The documentation for this class was generated from the following files:
include/utextfile.h
src/ufile/utextfile.cpp