ulib: ulib::CUTree Class Reference
ulib::CUTree Class Reference
#include <utree.h>
Public Member Functions
CUTree (int arg_verbose=0)
~CUTree ()
int GetNumNode ()
CUTreeNode * GetRootNode ()
bool IsEmpty ()
CUTreeNode * AddChildNode (CUTreeNode *parent)
void Verbose (int arg_verbose=0)
void Clear ()
void Print (FILE *fp, CUTreeNode *node, int level)
Constructor & Destructor Documentation
ulib::CUTree::CUTree (int arg_verbose = 0)
References Verbose().
ulib::CUTree::~CUTree ()
References Clear().
Member Function Documentation
CUTreeNode * ulib::CUTree::AddChildNode (CUTreeNode * parent)
References ulib::CUTreeNode::AddChild(), and ulib::CUTreeNode::parent.
void ulib::CUTree::Clear ()
References ulib::CUList::GetSize(), and ulib::CUList::PopFront().
Referenced by ~CUTree().
int ulib::CUTree::GetNumNode ()
References ulib::CUList::GetSize().
CUTreeNode * ulib::CUTree::GetRootNode ()
References ulib::CUList::GetAt().
Referenced by Print().
bool ulib::CUTree::IsEmpty ()
References ulib::CUList::GetSize().
void ulib::CUTree::Print (FILE * fp, CUTreeNode * node = NULL, int level = -1)
References ulib::CUTreeNode::child_list, ulib::CUTreeNode::GetChild(), GetRootNode(), ulib::CUList::GetSize(), and ulib::CUNode::id.
void ulib::CUTree::Verbose (int arg_verbose = 0)
Referenced by CUTree().
The documentation for this class was generated from the following files:
include/utree.h
src/uadt/utree.cpp