ulib: ulib::CUStringNode Class Reference
ulib::CUStringNode Class Reference
#include <ustringnode.h>
Public Member Functions
CUStringNode ()
~CUStringNode ()
bool SetData (char *arg_str)
bool SetData (CUString &arg_str)
char * GetData ()
Public Member Functions inherited from ulib::CUNode
CUNode ()
~CUNode ()
bool SetData (void *arg_data, short arg_data_size)
bool GetData (void *ret_data)
void Clear ()
bool IsEmpty ()
void Verbose (int arg_verbose)
Additional Inherited Members
Public Attributes inherited from ulib::CUNode
int id
void * data
size_t data_size
Constructor & Destructor Documentation
ulib::CUStringNode::CUStringNode ()
ulib::CUStringNode::~CUStringNode ()
Member Function Documentation
char * ulib::CUStringNode::GetData ()
References ulib::CUNode::data, and ulib::CUNode::data_size.
bool ulib::CUStringNode::SetData (char * arg_str)
Referenced by SetData().
bool ulib::CUStringNode::SetData (CUString & arg_str)
References ulib::CUString::GetStr(), and SetData().
The documentation for this class was generated from the following files:
include/ustringnode.h
src/uadt/ustringnode.cpp