ulib: ulib::CUStringList Class Reference
ulib::CUStringList Class Reference
StringList 클래스
#include <ustringlist.h>
Public Member Functions
CUStringList ()
생성자
CUStringList (CUString str, CUString delimeter)
생성자
~CUStringList ()
소멸자
void PushFront (const CUString &arg_str)
void PushBack (const CUString &arg_str)
void RemoveFront ()
void RemoveBack ()
bool IsEmpty ()
비어있는지 체크
int Find (char str[])
bool PopFront (CUString &ret_str)
bool PopBack (CUString &ret_str)
bool PopAt (int nPos, CUString &ret_str)
bool PopAt (int nPos)
bool GetAt (int nPos, CUString &ret_str)
char * GetAt (int nPos)
bool SetAt (int nPos, CUString &str)
bool SetAt (int nPos, char *str)
void TokenizeByChar (CUString str, CUString delimeter, bool permit_empty=true)
void TokenizeByStr (CUString str, CUString delimeter, bool permit_empty=true)
void TokenizeByBoundTag (CUString str, CUString open_tag, CUString close_tag, bool permit_empty=true)
void GetIntersection (CUStringList &list1, CUStringList &list2)
CUString ToString (char delimeter[]=" ")
void Print (FILE *fp, char delimeter[]="\n")
void PrintEx (FILE *fp, char delimeter[]="\n")
void Clear ()
list를 비움
Public Member Functions inherited from ulib::CUList
CUList (int arg_verbose=0)
생성자
~CUList ()
소멸자
long GetSize ()
list의 크기를 구함
void Verbose (int arg_verbose=0)
메시지를 화면에 출력할 정도를 설정
long PushFront (void *push_data, short data_size)
data를 list의 제일 앞에 추가
long PushBack (void *push_data, short data_size)
data를 list의 제일 뒤에 추가
long PushFront (char *push_data)
char *를 list의 제일 앞에 추가
long PushBack (char *push_data)
char*를 list의 제일 뒤에 추가
bool PopFront (void *ret_data)
처음 node의 data를 가져오고 list에서 삭제
bool PopBack (void *ret_data)
마지막 node의 data를 가져오고 list에서 삭제
bool PopAt (long nPos, void *ret_data)
임의의 위치의 node의 data를 가져오고 list에서 삭제
bool GetAt (long nPos, void *ret_data)
임의의 위치의 node의 data를 가져옴
bool GetCurNodeData (void *ret_data)
현재 선택된 node의 data를 구함
void MoveToStart ()
List의 제일 처음 node를 가리키게 설정
void MoveToEnd ()
list의 제일 끝 node를 가리키게 설정
bool MoveToNext ()
다음 node를 가리키게 설정
bool MoveToPrev ()
이전 node를 가리키게 설정
Detailed Description
StringList 클래스
Date
08.05.06
Author
이승욱
Warning
???
Bug:
???
Note
???
Constructor & Destructor Documentation
ulib::CUStringList::CUStringList ()
생성자
ulib::CUStringList::CUStringList (CUString str, CUString delimeter)
생성자
Parameters
str 초기 문자열
delimeter 초기 문자열을 나눌 문자들
References TokenizeByChar().
ulib::CUStringList::~CUStringList ()
소멸자
References Clear().
Member Function Documentation
void ulib::CUStringList::Clear ()
list를 비움
Reimplemented from ulib::CUList.
References PopFront().
Referenced by ulib::CUDir::GetFileList(), GetIntersection(), TokenizeByBoundTag(), TokenizeByChar(), TokenizeByStr(), and ~CUStringList().
int ulib::CUStringList::Find (char str[])
References GetAt(), and ulib::CUList::GetSize().
Referenced by GetIntersection().
bool ulib::CUStringList::GetAt (int nPos, CUString & ret_str)
References ulib::CUList::GetAt(), ulib::CUString::GetStr(), and ulib::CUString::SetStr().
Referenced by Find(), ulib::CUFlistFile::GetFilename(), GetIntersection(), ulib::CUIndexFile::Load(), Print(), PrintEx(), and ToString().
char * ulib::CUStringList::GetAt (int nPos)
References ulib::CUList::GetAt(), and ulib::CUString::GetStr().
void ulib::CUStringList::GetIntersection (CUStringList & list1, CUStringList & list2)
References Clear(), Find(), GetAt(), ulib::CUList::GetSize(), and PushBack().
bool ulib::CUStringList::IsEmpty ()
비어있는지 체크
Returns
비어있다면 true
See Also
GetSize(), Clear()
Reimplemented from ulib::CUList.
References ulib::CUList::GetSize().
bool ulib::CUStringList::PopAt (int nPos, CUString & ret_str)
References ulib::CUString::GetStr(), ulib::CUList::PopAt(), and ulib::CUString::SetStr().
bool ulib::CUStringList::PopAt (int nPos)
References ulib::CUList::PopAt().
bool ulib::CUStringList::PopBack (CUString & ret_str)
References ulib::CUString::GetStr(), ulib::CUList::PopBack(), and ulib::CUString::SetStr().
Referenced by RemoveBack().
bool ulib::CUStringList::PopFront (CUString & ret_str)
References ulib::CUString::GetStr(), ulib::CUList::PopFront(), and ulib::CUString::SetStr().
Referenced by Clear(), and RemoveFront().
void ulib::CUStringList::Print (FILE * fp, char delimeter[] = "\n")
References GetAt(), and ulib::CUList::GetSize().
void ulib::CUStringList::PrintEx (FILE * fp, char delimeter[] = "\n")
References GetAt(), and ulib::CUList::GetSize().
void ulib::CUStringList::PushBack (const CUString & arg_str)
Referenced by ulib::CUDir::GetFileList(), GetIntersection(), ulib::CUIndexFile::GetKeyList(), ulib::CUFlistFile::Open(), TokenizeByBoundTag(), TokenizeByChar(), and TokenizeByStr().
void ulib::CUStringList::PushFront (const CUString & arg_str)
void ulib::CUStringList::RemoveBack ()
References PopBack().
void ulib::CUStringList::RemoveFront ()
References PopFront().
bool ulib::CUStringList::SetAt (int nPos, CUString & str)
References ulib::CUList::GetAt().
Referenced by SetAt().
bool ulib::CUStringList::SetAt (int nPos, char * str)
References SetAt().
void ulib::CUStringList::TokenizeByBoundTag (CUString str, CUString open_tag, CUString close_tag, bool permit_empty = true)
References Clear(), ulib::CUString::Find(), ulib::CUString::GetLength(), ulib::CUString::GetStr(), PushBack(), and ulib::CUString::SubStr().
void ulib::CUStringList::TokenizeByChar (CUString str, CUString delimeter, bool permit_empty = true)
References Clear(), ulib::CUString::Find(), ulib::CUString::GetAt(), ulib::CUString::GetLength(), ulib::CUString::IsEmpty(), ulib::CUString::Left(), ulib::CUString::Mid(), and PushBack().
Referenced by CUStringList().
void ulib::CUStringList::TokenizeByStr (CUString str, CUString delimeter, bool permit_empty = true)
References Clear(), ulib::CUString::Find(), ulib::CUString::GetLength(), ulib::CUString::GetStr(), ulib::CUString::IsEmpty(), ulib::CUString::Left(), ulib::CUString::Mid(), and PushBack().
CUString ulib::CUStringList::ToString (char delimeter[] = " ")
References GetAt(), and ulib::CUList::GetSize().
The documentation for this class was generated from the following files:
include/ustringlist.h
src/ustring/ustringlist.cpp