ulib: ulib::CUProgress Class Reference
ulib::CUProgress Class Reference
#include <uprogress.h>
Public Member Functions
CUProgress ()
void Begin ()
void End ()
double GetElapsedSec ()
double GetElapsedSec (clock_t now_clock)
void SetMaxCount (int max_cnt)
float GetPercent (int now_cnt)
void PrintPercent (FILE *fp, int now_cnt, char msg[]="\n")
void PrintElapsedTime (FILE *fp)
Constructor & Destructor Documentation
ulib::CUProgress::CUProgress ()
Member Function Documentation
void ulib::CUProgress::Begin ()
void ulib::CUProgress::End ()
double ulib::CUProgress::GetElapsedSec ()
Referenced by PrintElapsedTime(), and PrintPercent().
double ulib::CUProgress::GetElapsedSec (clock_t now_clock)
float ulib::CUProgress::GetPercent (int now_cnt)
Referenced by PrintPercent().
void ulib::CUProgress::PrintElapsedTime (FILE * fp)
References GetElapsedSec(), and ulib::CUString::SetColor().
void ulib::CUProgress::PrintPercent (FILE * fp, int now_cnt, char msg[] = "\n")
References GetElapsedSec(), GetPercent(), ulib::CUString::GetStr(), and ulib::CUString::SetColor().
void ulib::CUProgress::SetMaxCount (int max_cnt)
The documentation for this class was generated from the following files:
include/uprogress.h
src/uutil/uprogress.cpp