ulib: ulib::CUOption Class Reference
ulib::CUOption Class Reference
#include <uoption.h>
Public Member Functions
CUOption ()
bool Load (int argc, char *argv[])
void Print (FILE *fp)
bool GetValue (CUString &key, CUString &value)
Public Attributes
map< string, string > option_map
CUConfigFile conf_file
Constructor & Destructor Documentation
ulib::CUOption::CUOption ()
Member Function Documentation
bool ulib::CUOption::GetValue (CUString & key, CUString & value)
References ulib::CUString::GetStr().
bool ulib::CUOption::Load (int argc, char * argv[])
References ulib::CUString::GetAt(), ulib::CUString::GetStr(), and ulib::CUString::Mid().
void ulib::CUOption::Print (FILE * fp)
Member Data Documentation
CUConfigFile ulib::CUOption::conf_file
map<string, string> ulib::CUOption::option_map
The documentation for this class was generated from the following files:
include/uoption.h
src/uutil/uoption.cpp