ulib: ulib::CUDir Class Reference
ulib::CUDir Class Reference
#include <udir.h>
Public Member Functions
CUDir ()
CUDir (char arg_dirname[])
CUDir (CUString arg_dirname)
~CUDir ()
bool OpenDir (char arg_dirname[])
void CloseDir ()
bool IsOpen ()
bool ReadFile (CUString &arg_file)
void MoveToStart ()
bool GetFileList (CUStringList &list, char extension[]="")
CUString GetDirName ()
size_t GetNumFile ()
Static Public Member Functions
static CUString ExtractFilename (CUString &path)
static CUString ExtractFilename (char path[])
static CUString ExtractExtension (CUString &file)
static CUString ExtractExtension (char *file)
Constructor & Destructor Documentation
ulib::CUDir::CUDir ()
Referenced by CUDir().
ulib::CUDir::CUDir (char arg_dirname[])
References CUDir(), and OpenDir().
ulib::CUDir::CUDir (CUString arg_dirname)
References ulib::CUString::GetStr(), and OpenDir().
ulib::CUDir::~CUDir ()
References CloseDir(), and IsOpen().
Member Function Documentation
void ulib::CUDir::CloseDir ()
Referenced by ~CUDir().
CUString ulib::CUDir::ExtractExtension (CUString & file) static
References ulib::CUString::Mid(), and ulib::CUString::ReverseFind().
Referenced by ExtractExtension(), and GetFileList().
CUString ulib::CUDir::ExtractExtension (char * file) static
References ExtractExtension().
CUString ulib::CUDir::ExtractFilename (CUString & path) static
References ulib::CUString::Mid(), and ulib::CUString::ReverseFind().
Referenced by ExtractFilename().
CUString ulib::CUDir::ExtractFilename (char path[]) static
References ExtractFilename().
CUString ulib::CUDir::GetDirName ()
Referenced by GetFileList().
bool ulib::CUDir::GetFileList (CUStringList & list, char extension[] = "")
References ulib::CUStringList::Clear(), ExtractExtension(), GetDirName(), ulib::CUString::IsEmpty(), IsOpen(), MoveToStart(), ulib::CUStringList::PushBack(), and ReadFile().
size_t ulib::CUDir::GetNumFile ()
References ulib::CUString::GetStr(), IsOpen(), and MoveToStart().
bool ulib::CUDir::IsOpen ()
Referenced by GetFileList(), GetNumFile(), ReadFile(), and ~CUDir().
void ulib::CUDir::MoveToStart ()
Referenced by GetFileList(), and GetNumFile().
bool ulib::CUDir::OpenDir (char arg_dirname[])
References ulib::CUString::TrimRight().
Referenced by CUDir().
bool ulib::CUDir::ReadFile (CUString & arg_file)
References ulib::CUString::GetStr(), and IsOpen().
Referenced by GetFileList().
The documentation for this class was generated from the following files:
include/udir.h
src/ufile/udir.cpp