ulib: ulib::CUStringListRO Class Reference
ulib::CUStringListRO Class Reference
StringList 클래스, Null로 나누어져 있어 빠름.
#include <ustringlistro.h>
Public Member Functions
CUStringListRO ()
Constructor.
CUStringListRO (const CUString &str, const CUString &delimeter)
Constructor.
~CUStringListRO ()
소멸자
size_t GetSize ()
char * GetAt (int nPos)
void MakeList (const CUString &arg_str, CUString delimeter)
void Clear ()
Public Attributes
CUString str
int * pos
size_t size
Detailed Description
StringList 클래스, Null로 나누어져 있어 빠름.
Date
06.08.14
Author
이승욱
Warning
???
Bug:
???
Note
???
Constructor & Destructor Documentation
ulib::CUStringListRO::CUStringListRO ()
Constructor.
References pos.
Referenced by CUStringListRO().
ulib::CUStringListRO::CUStringListRO (const CUString & str, const CUString & delimeter)
Constructor.
Parameters
str 초기 문자열
delimeter 초기 문자열을 나눌 문자들
References CUStringListRO(), and MakeList().
ulib::CUStringListRO::~CUStringListRO ()
소멸자
References Clear().
Member Function Documentation
void ulib::CUStringListRO::Clear ()
References ulib::CUString::Empty(), pos, size, and str.
Referenced by ~CUStringListRO().
char * ulib::CUStringListRO::GetAt (int nPos)
References GetSize(), ulib::CUString::GetStr(), pos, and str.
size_t ulib::CUStringListRO::GetSize ()
References size.
Referenced by GetAt().
void ulib::CUStringListRO::MakeList (const CUString & arg_str, CUString delimeter)
References ulib::CUString::GetAt(), ulib::CUString::GetLength(), pos, ulib::CUString::SetAt(), size, and str.
Referenced by CUStringListRO().
Member Data Documentation
int* ulib::CUStringListRO::pos
Referenced by Clear(), CUStringListRO(), GetAt(), and MakeList().
size_t ulib::CUStringListRO::size
Referenced by Clear(), GetSize(), and MakeList().
CUString ulib::CUStringListRO::str
Referenced by Clear(), GetAt(), and MakeList().
The documentation for this class was generated from the following files:
include/ustringlistro.h
src/ustring/ustringlistro.cpp