ulib: ulib::CUJsonTokenList Class Reference
ulib::CUJsonTokenList Class Reference
#include <ujson.h>
Public Member Functions
void PushBack (CUString str)
CUJsonToken * GetAt (int i)
void Print ()
Public Member Functions inherited from ulib::CUList
CUList (int arg_verbose=0)
생성자
~CUList ()
소멸자
long GetSize ()
list의 크기를 구함
bool IsEmpty ()
비어있는지 체크
void Verbose (int arg_verbose=0)
메시지를 화면에 출력할 정도를 설정
long PushFront (void *push_data, short data_size)
data를 list의 제일 앞에 추가
long PushBack (void *push_data, short data_size)
data를 list의 제일 뒤에 추가
long PushFront (char *push_data)
char *를 list의 제일 앞에 추가
long PushBack (char *push_data)
char*를 list의 제일 뒤에 추가
bool PopFront (void *ret_data)
처음 node의 data를 가져오고 list에서 삭제
bool PopBack (void *ret_data)
마지막 node의 data를 가져오고 list에서 삭제
bool PopAt (long nPos, void *ret_data)
임의의 위치의 node의 data를 가져오고 list에서 삭제
bool GetAt (long nPos, void *ret_data)
임의의 위치의 node의 data를 가져옴
void Clear ()
list를 비움
bool GetCurNodeData (void *ret_data)
현재 선택된 node의 data를 구함
void MoveToStart ()
List의 제일 처음 node를 가리키게 설정
void MoveToEnd ()
list의 제일 끝 node를 가리키게 설정
bool MoveToNext ()
다음 node를 가리키게 설정
bool MoveToPrev ()
이전 node를 가리키게 설정
Member Function Documentation
CUJsonToken * ulib::CUJsonTokenList::GetAt (int i)
References ulib::CUList::GetAt().
Referenced by ulib::CUJson::MatchBrace(), and Print().
void ulib::CUJsonTokenList::Print ()
References GetAt(), ulib::CUList::GetSize(), ulib::CUString::GetStr(), ulib::CUJsonToken::lexical, and ulib::CUJsonToken::match_idx.
void ulib::CUJsonTokenList::PushBack (CUString str)
References ulib::CUJsonToken::lexical.
Referenced by ulib::CUJson::Tokenize().
The documentation for this class was generated from the following files:
include/ujson.h
src/uparser/ujson.cpp