ulib: ulib::CUFlistFile Class Reference
ulib::CUFlistFile Class Reference
#include <uflistfile.h>
Public Member Functions
CUFlistFile (CUString arg_filename)
CUFlistFile (char *arg_filename)
~CUFlistFile ()
bool Open (CUString arg_filename)
bool Open (char *arg_filename)
bool IsOpen ()
bool CheckOpen ()
bool CheckList (bool print)
bool GetFileContent (int i, CUString &str)
char * GetFilename (int i)
int GetNumFile ()
Constructor & Destructor Documentation
ulib::CUFlistFile::CUFlistFile (CUString arg_filename)
References ulib::CUString::GetStr().
ulib::CUFlistFile::CUFlistFile (char * arg_filename)
References Open().
ulib::CUFlistFile::~CUFlistFile ()
Member Function Documentation
bool ulib::CUFlistFile::CheckList (bool print)
References GetFilename(), GetNumFile(), and ulib::CUTextFile::IsOpen().
bool ulib::CUFlistFile::CheckOpen ()
References ulib::CUTextFile::CheckOpen().
bool ulib::CUFlistFile::GetFileContent (int i, CUString & str)
References GetFilename(), ulib::CUTextFile::IsOpen(), and ulib::CUTextFile::LoadToStr().
char * ulib::CUFlistFile::GetFilename (int i)
References ulib::CUStringList::GetAt(), and ulib::CUList::GetSize().
Referenced by CheckList(), and GetFileContent().
int ulib::CUFlistFile::GetNumFile ()
References ulib::CUList::GetSize().
Referenced by CheckList().
bool ulib::CUFlistFile::IsOpen ()
References ulib::CUTextFile::IsOpen().
bool ulib::CUFlistFile::Open (CUString arg_filename)
References ulib::CUString::GetStr().
Referenced by CUFlistFile().
bool ulib::CUFlistFile::Open (char * arg_filename)
References ulib::CUTextFile::OpenFile(), ulib::CUStringList::PushBack(), and ulib::CUTextFile::ReadLine().
The documentation for this class was generated from the following files:
include/uflistfile.h
src/ufile/uflistfile.cpp