ulib: ulib::CUCounter Class Reference
ulib::CUCounter Class Reference
#include <ucounter.h>
Classes
class _str_cnt
class _str_cnt_less
Public Member Functions
CUCounter ()
unsigned long GetNumItem ()
unsigned long GetTotalCount ()
void AddItem (char *item, unsigned long num=1)
void AddItem (long item, unsigned long num=1)
bool GetCount (char *item, unsigned long &ret)
void Print (FILE *fp, char mode[]="IC", char sort='I')
Public Attributes
std::map< std::string,
unsigned long > str_cnt_map
Constructor & Destructor Documentation
ulib::CUCounter::CUCounter ()
Member Function Documentation
void ulib::CUCounter::AddItem (char * item, unsigned long num = 1)
References str_cnt_map.
Referenced by AddItem().
void ulib::CUCounter::AddItem (long item, unsigned long num = 1)
References AddItem().
bool ulib::CUCounter::GetCount (char * item, unsigned long & ret)
References str_cnt_map.
unsigned long ulib::CUCounter::GetNumItem ()
References str_cnt_map.
unsigned long ulib::CUCounter::GetTotalCount ()
Referenced by Print().
void ulib::CUCounter::Print (FILE * fp, char mode[] = "IC", char sort = 'I')
References GetTotalCount(), and str_cnt_map.
Member Data Documentation
std::map<std::string, unsigned long> ulib::CUCounter::str_cnt_map
Referenced by AddItem(), GetCount(), GetNumItem(), and Print().
The documentation for this class was generated from the following files:
include/ucounter.h
src/uutil/ucounter.cpp