ulib: ulib::CUJson Class Reference
ulib::CUJson Class Reference
#include <ujson.h>
Public Member Functions
CUJson ()
~CUJson ()
virtual bool Load (CUString &str)
virtual bool ToString (CUString &ret)
bool Tokenize ()
bool MatchBrace (int start_idx, int end_idx)
bool Parse (int start_idx, int end_idx)
Public Member Functions inherited from ulib::CUParser
CUParser ()
~CUParser ()
Public Attributes
CUString str
CUJsonTokenList token_list
CUJsonContainer container
Constructor & Destructor Documentation
ulib::CUJson::CUJson ()
References container, and ulib::CUJsonContainer::name.
ulib::CUJson::~CUJson ()
Member Function Documentation
bool ulib::CUJson::Load (CUString & str) virtual
References MatchBrace(), Parse(), str, and Tokenize().
bool ulib::CUJson::MatchBrace (int start_idx = -1, int end_idx = -1)
References ulib::CUJsonTokenList::GetAt(), ulib::CUList::GetSize(), ulib::CUJsonToken::lexical, ulib::CUJsonToken::match_idx, and token_list.
Referenced by Load().
bool ulib::CUJson::Parse (int start_idx = -1, int end_idx = -1)
References ulib::CUList::GetSize(), and token_list.
Referenced by Load().
bool ulib::CUJson::Tokenize ()
References ulib::CUList::Clear(), ulib::CUString::Find(), ulib::CUString::GetAt(), ulib::CUString::GetLength(), ulib::CUJsonTokenList::PushBack(), str, ulib::CUString::SubStr(), and token_list.
Referenced by Load().
bool ulib::CUJson::ToString (CUString & ret) virtual
Reimplemented from ulib::CUParser.
Member Data Documentation
CUJsonContainer ulib::CUJson::container
Referenced by CUJson().
CUString ulib::CUJson::str
Referenced by Load(), and Tokenize().
CUJsonTokenList ulib::CUJson::token_list
Referenced by MatchBrace(), Parse(), and Tokenize().
The documentation for this class was generated from the following files:
include/ujson.h
src/uparser/ujson.cpp