ulib: ulib::CUFile Class Reference
ulib::CUFile Class Reference
#include <ufile.h>
Public Member Functions
CUFile (int verbosity=0)
CUFile (CUString arg_file_name, CUString arg_file_mode="rb", int verbosity=0)
~CUFile ()
void Verbosity (int arg_verbosity)
bool IsOpen ()
bool OpenFile (CUString arg_file_name, CUString arg_file_mode="r")
void CloseFile ()
bool ReopenFile (CUString arg_file_name, CUString arg_file_mode="r")
FILE * GetFP ()
void MoveToStart ()
void MoveToEnd ()
long GetFileSize ()
CUString GetFileName ()
CUString GetFileMode ()
Static Public Member Functions
static long GetFileSize (CUString filename)
static long GetFileSize (char filename[])
Constructor & Destructor Documentation
ulib::CUFile::CUFile (int verbosity = 0)
References Verbosity().
ulib::CUFile::CUFile (CUString arg_file_name, CUString arg_file_mode = "rb", int verbosity = 0)
References OpenFile(), and Verbosity().
ulib::CUFile::~CUFile ()
References CloseFile().
Member Function Documentation
void ulib::CUFile::CloseFile ()
Referenced by ReopenFile(), and ~CUFile().
CUString ulib::CUFile::GetFileMode ()
CUString ulib::CUFile::GetFileName ()
long ulib::CUFile::GetFileSize ()
Referenced by GetFileSize().
long ulib::CUFile::GetFileSize (CUString filename) static
References GetFileSize(), and ulib::CUString::GetStr().
long ulib::CUFile::GetFileSize (char filename[]) static
FILE * ulib::CUFile::GetFP ()
bool ulib::CUFile::IsOpen ()
Referenced by MoveToEnd(), and MoveToStart().
void ulib::CUFile::MoveToEnd ()
References IsOpen().
Referenced by OpenFile().
void ulib::CUFile::MoveToStart ()
References IsOpen().
Referenced by OpenFile().
bool ulib::CUFile::OpenFile (CUString arg_file_name, CUString arg_file_mode = "r")
References ulib::CUString::GetStr(), ulib::CUString::IsEmpty(), MoveToEnd(), and MoveToStart().
Referenced by CUFile(), and ReopenFile().
bool ulib::CUFile::ReopenFile (CUString arg_file_name, CUString arg_file_mode = "r")
References CloseFile(), ulib::CUString::GetStr(), and OpenFile().
void ulib::CUFile::Verbosity (int arg_verbosity)
Referenced by CUFile().
The documentation for this class was generated from the following files:
include/ufile.h
src/ufile/ufile.cpp