ulib: ulib::CUIndexFile Class Reference
ulib::CUIndexFile Class Reference
#include <uindexfile.h>
Public Member Functions
CUIndexFile ()
~CUIndexFile ()
bool Load (char *prefix)
bool IsLoaded ()
void Close ()
int GetNumRecord ()
CUStringList GetKeyList ()
bool HaveKey (char *key)
bool GetInfo (char *key, CUIndexFileInfo &info)
bool GetInfo (char *key, unsigned long &start, unsigned long &end)
bool GetValue (char *key, CUString &ret)
bool GetValue (CUIndexFileInfo info, CUString &ret)
bool GetValue (char *key, void *ret)
bool GetValue (CUIndexFileInfo info, void *ret)
bool Create (char *prefix)
bool Insert (char *key, char *value)
bool Insert (char *key, char *value, int len)
Public Attributes
map< string, CUIndexFileInfo > info_map
Constructor & Destructor Documentation
ulib::CUIndexFile::CUIndexFile ()
ulib::CUIndexFile::~CUIndexFile ()
References Close().
Member Function Documentation
void ulib::CUIndexFile::Close ()
References ulib::CUTextFile::CloseFile(), and ulib::CUTextFile::IsOpen().
Referenced by Create(), Load(), and ~CUIndexFile().
bool ulib::CUIndexFile::Create (char * prefix)
References Close(), and ulib::CUTextFile::OpenFile().
bool ulib::CUIndexFile::GetInfo (char * key, CUIndexFileInfo & info)
References info_map.
Referenced by GetValue().
bool ulib::CUIndexFile::GetInfo (char * key, unsigned long & start, unsigned long & end)
CUStringList ulib::CUIndexFile::GetKeyList ()
References info_map, and ulib::CUStringList::PushBack().
int ulib::CUIndexFile::GetNumRecord () inline
bool ulib::CUIndexFile::GetValue (char * key, CUString & ret)
References GetInfo().
Referenced by GetValue().
bool ulib::CUIndexFile::GetValue (CUIndexFileInfo info, CUString & ret)
References ulib::CUIndexFileInfo::enable, ulib::CUIndexFileInfo::end, ulib::CUTextFile::GetFP(), IsLoaded(), and ulib::CUIndexFileInfo::start.
bool ulib::CUIndexFile::GetValue (char * key, void * ret)
References GetInfo(), and GetValue().
bool ulib::CUIndexFile::GetValue (CUIndexFileInfo info, void * ret)
References ulib::CUIndexFileInfo::enable, ulib::CUIndexFileInfo::end, ulib::CUTextFile::GetFP(), IsLoaded(), and ulib::CUIndexFileInfo::start.
bool ulib::CUIndexFile::HaveKey (char * key)
bool ulib::CUIndexFile::Insert (char * key, char * value)
References ulib::CUIndexFileInfo::end, ulib::CUTextFile::GetFP(), info_map, IsLoaded(), and ulib::CUIndexFileInfo::start.
bool ulib::CUIndexFile::Insert (char * key, char * value, int len)
References ulib::CUIndexFileInfo::end, ulib::CUTextFile::GetFP(), info_map, IsLoaded(), and ulib::CUIndexFileInfo::start.
bool ulib::CUIndexFile::IsLoaded ()
References ulib::CUTextFile::IsOpen().
Referenced by GetValue(), and Insert().
bool ulib::CUIndexFile::Load (char * prefix)
References Close(), ulib::CUIndexFileInfo::enable, ulib::CUIndexFileInfo::end, ulib::CUStringList::GetAt(), ulib::CUList::GetSize(), ulib::CUString::GetStr(), info_map, ulib::CUTextFile::OpenFile(), ulib::CUTextFile::ReadLine(), and ulib::CUIndexFileInfo::start.
Member Data Documentation
map<string, CUIndexFileInfo> ulib::CUIndexFile::info_map
Referenced by GetInfo(), GetKeyList(), Insert(), and Load().
The documentation for this class was generated from the following files:
include/uindexfile.h
src/ufile/uindexfile.cpp